config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'workers/index'
  root to: "workers#index"

  resources :workers, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: :create 
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :worker
  belongs_to :user 

  validates :content,       presence: true
  validates :content_title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name,       presence: true
  validates :profile,    presence: true
  validates :occupation, presence: true
  validates :position,   presence: true
  
  has_many :workers
  has_many :comments
end

app/models/worker.rb
class Worker < ApplicationRecord
  belongs_to :user
  #has_one_attached :image
  has_many :comments, dependent: :destroy

  validates :title,       presence: true
  validates :catch_copy,  presence: true
  validates :pt_name,     presence: true
  #validates :image,       presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :occupation, :position])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to worker_path(@comment.worker) 
    else
      @worker = @comment.worker
      @comments = @worker.comments
      render "workers/show" 
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :content_title).merge(user_id: current_user.id, worker_id: params[:worker_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @workers = @user.workers
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :destroy]

  def index
    @workers = Worker.includes(:user)
  end

  def new
    @worker = Worker.new
  end

  def create
    @worker = Worker.new(worker_params)
    if @worker.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @worker = Worker.find(params[:id])
    @comment = Comment.new
    @comments = @worker.comments
  end

  def edit
    @worker = Worker.find(params[:id])
  end

  def update
    @worker = Worker.find(params[:id])
    if @worker.update(worker_params)
      redirect_to worker_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    worker = Worker.find(params[:id])
    worker.destroy
    redirect_to root_path
  end

  private
  def worker_params
    params.require(:worker).permit(:title, :catch_copy, :pt_name, :image).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/_gpt.html.erb
  <!DOCTYPE html>
  <html lang="ja">
    <head>
      <meta charset="UTF-8" />
      <meta
        name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
      />
      <meta http-equiv="X-UA-Compatible" content="ie=edge" />
      <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.3.4/axios.min.js"></script>
      <title>Document</title>
    </head>
    <body>
      <main>
        <p>テキストを入力して送信ボタンを押すと、ChatGPTが返答を生成し、VOICEVOXがその返答を音声化します。</p>
        <div class="input-area">
          <div class="cp_iptxt">
            <label class="ef">
            <input type="text" placeholder="AIにメッセージを送る" name="talk" />
          </div>
          <button type="button" class="send">送信</button>
          <%= link_to image_tag("border.png", class: :frame), root_path %>
        </div>
        <audio class="audio"></audio>
        <div class="chat-log"></div>
      </main>
      <script>
        // TODO: OpenAI API キーを入力
        const api_key = "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";
        let lastResponse = null; // 追加

        const sendButton = document.querySelector(".send");
        sendButton.addEventListener("click", async () => {
          const text = document.querySelector("[name=talk]");
          const responseText = await requestChatAPI(text.value);
          addChatLog(`User: ${text.value}`);
          addChatLog(`ChatGPT: ${responseText}`);
          await createAudio(responseText);
        });

        function addChatLog(message) {
          const chatLog = document.querySelector('.chat-log');
          chatLog.innerHTML += `<p>${message}</p>`;
        }

        async function requestChatAPI(text) {
          const headers = {
            "Content-Type": "application/json",
            Authorization: `Bearer ${api_key}`,
          };

          const messages = [
            {
              role: "system",
              content: "ゴルゴ13を必ず演じてください。喜怒哀楽の表現をほとんど見せず、言葉数は少なく、必ずデューク東郷に成り切って喋り口調で会話してください"
            },
            {
              role: "user",
              content: text,
            },
          ];

          // 最後の応答が存在する場合、それをメッセージリストに追加します。
          if (lastResponse) {
            messages.unshift({
              role: "assistant",
              content: lastResponse,
            });
          }

          const payload = {
            model: "gpt-3.5-turbo",
            max_tokens: 128,
            messages: messages,
          };
          const response = await axios.post(
            "https://api.openai.com/v1/chat/completions",
            payload,
            {
              headers: headers,
            }
          );

          // 応答を保存します。
          lastResponse = response.data.choices[0].message.content;

          return lastResponse;
        }

        async function createAudio(text) {
          const data = await createVoice(text);
          const audio = document.querySelector(".audio");
          audio.src = URL.createObjectURL(data);
          audio.play();
        }
        async function createQuery(text) {
          const response = await axios.post(
            `http://localhost:50021/audio_query?speaker=1&text=${text}`
          );
          return response.data;
        }
        async function createVoice(text) {
          const query = await createQuery(text);
          const response = await axios.post(
            "http://localhost:50021/synthesis?speaker=1",
            query,
            { responseType: "blob" }
          );
          return response.data;
        }
      </script>
    </body>
  </html>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Case_Worker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: :nav__logout %>
              <%= link_to "新規投稿", new_worker_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © CASE WORKER All rights reserved.</p>
    </footer>
    </body>
  </body>
</html>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= @user.occupation %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= @user.position %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんのプロトタイプ"%>
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
        <% @workers.each do |worker| %>
          <%= render 'workers/prototype', worker: worker %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/workers/_form.html.erb
<%= form_with model: @worker, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "説明文" %><br />
    <%= f.text_area :catch_copy, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :pt_name, "患者名" %><br />
    <%= f.text_area :pt_name, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/workers/_prototype.html.erb
<div class="card">
  <%# link_to image_tag(worker.image, class: :card__img ), worker_path(worker)%>
  <div class="card__body">
    <%= link_to worker.title, worker_path(worker), class: 'card__title' %>
    <p class="card__summary">
      <%= worker.catch_copy %>
    </p>
    <%= worker.pt_name %>
    <%= link_to worker.user.name, "/users/#{worker.user.id}", class: 'card__user' %>
  </div>
</div>

app/views/workers/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: "form", locals: { worker: @worker } %>
    </div>
  </div>
</div>

app/views/workers/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
    <% if user_signed_in? %>
      <div class="greeting">こんにちは、
        <%= link_to current_user.name, "/users/#{current_user.id}", class: :greeting__link%>さん。AIと相談することができます。
      </div>
      <!DOCTYPE html>
      <html lang="ja">
        <head>
          <meta charset="UTF-8" />
          <meta
            name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
          />
          <meta http-equiv="X-UA-Compatible" content="ie=edge" />
          <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.3.4/axios.min.js"></script>
          <title>Document</title>
        </head>
        <body>
          <main>
            <p>テキストを入力して送信ボタンを押すと、ChatGPTが返答を生成し、VOICEVOXがその返答を音声化します。</p>
            <div class="input-area">
              <div class="cp_iptxt">
                <label class="ef">
                <input type="text" placeholder="AIにメッセージを送る" name="talk" />
              </div>
              <button type="button" class="send">送信</button>
              <%= link_to image_tag("border.png", class: :frame), root_path %>
            </div>
            <audio class="audio"></audio>
            <div class="chat-log"></div>
          </main>
          <script>
            // TODO: OpenAI API キーを入力
            const api_key = "sk-";
            let lastResponse = null; // 追加

            const sendButton = document.querySelector(".send");
            sendButton.addEventListener("click", async () => {
              const text = document.querySelector("[name=talk]");
              const responseText = await requestChatAPI(text.value);
              addChatLog(`User: ${text.value}`);
              addChatLog(`ChatGPT: ${responseText}`);
              await createAudio(responseText);
            });

            function addChatLog(message) {
              const chatLog = document.querySelector('.chat-log');
              chatLog.innerHTML += `<p>${message}</p>`;
            }

            async function requestChatAPI(text) {
              const headers = {
                "Content-Type": "application/json",
                Authorization: `Bearer ${api_key}`,
              };

              const messages = [
                {
                  role: "system",
                  content: "ゴルゴ13を必ず演じてください。喜怒哀楽の表現をほとんど見せず、言葉数は少なく、必ずデューク東郷に成り切って喋り口調で会話してください彼のイメージは「無口」「冷静沈着」という言葉がぴったり、依頼を受ける際には「わかった、やってみよう…」と言う。本質的には「臆病な人間」であり、自分の能力や運を過信していない。仕事を請け負う際も、それが彼にとってどれほど簡単な依頼であっても「成功する前提」の安請け合いはせず、あくまで「自分は一介のスナイパーに過ぎない」というスタンスで依頼人と接する。"
                },
                {
                  role: "user",
                  content: text,
                },
              ];

              // 最後の応答が存在する場合、それをメッセージリストに追加します。
              if (lastResponse) {
                messages.unshift({
                  role: "assistant",
                  content: lastResponse,
                });
              }

              const payload = {
                model: "gpt-3.5-turbo",
                max_tokens: 128,
                messages: messages,
              };
              const response = await axios.post(
                "https://api.openai.com/v1/chat/completions",
                payload,
                {
                  headers: headers,
                }
              );

              // 応答を保存します。
              lastResponse = response.data.choices[0].message.content;

              return lastResponse;
            }

            async function createAudio(text) {
              const data = await createVoice(text);
              const audio = document.querySelector(".audio");
              audio.src = URL.createObjectURL(data);
              audio.play();
            }
            async function createQuery(text) {
              const response = await axios.post(
                `http://localhost:50021/audio_query?speaker=1&text=${text}`
              );
              return response.data;
            }
            async function createVoice(text) {
              const query = await createQuery(text);
              const response = await axios.post(
                "http://localhost:50021/synthesis?speaker=1",
                query,
                { responseType: "blob" }
              );
              return response.data;
            }
          </script>
        </body>
      </html>
    <% end %>

    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
        <%= render partial: 'prototype', collection: @workers, as: :worker %>
    </div>
  </div>
</main>

app/views/workers/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規投稿</h2>
        <%= render partial: "form", locals: { worker: @worker } %>
    </div>
  </div>
</div>

app/views/workers/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">


          <!DOCTYPE html>
      <html lang="ja">
        <head>
          <meta charset="UTF-8" />
          <meta
            name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
          />
          <meta http-equiv="X-UA-Compatible" content="ie=edge" />
          <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.3.4/axios.min.js"></script>
          <title>Document</title>
        </head>
        <body>
          <main>
            <p>テキストを入力して送信ボタンを押すと、ChatGPTが返答を生成し、VOICEVOXがその返答を音声化します。</p>
            <div class="input-area">
              <div class="cp_iptxt">
                <label class="ef">
                <input type="text" placeholder="AIにメッセージを送る" name="talk" />
              </div>
              <button type="button" class="send">送信</button>
              <%= link_to image_tag("border.png", class: :frame), root_path %>
            </div>
            <audio class="audio"></audio>
            <div class="chat-log"></div>
          </main>
          <script>
            // TODO: OpenAI API キーを入力
            const api_key = "sk-";
            let lastResponse = null; // 追加

            const sendButton = document.querySelector(".send");
            sendButton.addEventListener("click", async () => {
              const text = document.querySelector("[name=talk]");
              const responseText = await requestChatAPI(text.value);
              addChatLog(`User: ${text.value}`);
              addChatLog(`ChatGPT: ${responseText}`);
              await createAudio(responseText);
            });

            function addChatLog(message) {
              const chatLog = document.querySelector('.chat-log');
              chatLog.innerHTML += `<p>${message}</p>`;
            }

            async function requestChatAPI(text) {
              const headers = {
                "Content-Type": "application/json",
                Authorization: `Bearer ${api_key}`,
              };

              const messages = [
                {
                  role: "system",
                  content: "ゴルゴ13を必ず演じてください。喜怒哀楽の表現をほとんど見せず、言葉数は少なく、必ずデューク東郷に成り切って喋り口調で会話してください"
                },
                {
                  role: "user",
                  content: text,
                },
              ];

              // 最後の応答が存在する場合、それをメッセージリストに追加します。
              if (lastResponse) {
                messages.unshift({
                  role: "assistant",
                  content: lastResponse,
                });
              }

              const payload = {
                model: "gpt-3.5-turbo",
                max_tokens: 128,
                messages: messages,
              };
              const response = await axios.post(
                "https://api.openai.com/v1/chat/completions",
                payload,
                {
                  headers: headers,
                }
              );

              // 応答を保存します。
              lastResponse = response.data.choices[0].message.content;

              return lastResponse;
            }

            async function createAudio(text) {
              const data = await createVoice(text);
              const audio = document.querySelector(".audio");
              audio.src = URL.createObjectURL(data);
              audio.play();
            }
            async function createQuery(text) {
              const response = await axios.post(
                `http://localhost:50021/audio_query?speaker=1&text=${text}`
              );
              return response.data;
            }
            async function createVoice(text) {
              const query = await createQuery(text);
              const response = await axios.post(
                "http://localhost:50021/synthesis?speaker=1",
                query,
                { responseType: "blob" }
              );
              return response.data;
            }
          </script>
        </body>
      </html>

      <p class="prototype__hedding">
        <%= @worker.title%>
      </p>
      <%= link_to @worker.user.name, "/users/#{@worker.user.id}", class: :prototype__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @worker.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_worker_path(@worker.id), class: :prototype__btn %>
          <%= link_to "削除する", worker_path(@worker), data: { turbo_method: :delete }, class: :prototype__btn %>
        </div>
      <% end %>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
        <%#= image_tag "プロトタイプの画像" %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">説明文</p>
          <p class="detail__message">
            <%= @worker.catch_copy %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">患者名</p>
          <p class="detail__message">
            <%=  @worker.pt_name %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
         <% if user_signed_in? %>
          <%= form_with model: [@worker, @comment],local: true do |f|%>
            <div class="field">
              <%= f.label :content_title, "タイトル" %><br />
              <%= f.text_field :content_title, id:"comment_content2" %><br />
              <%= f.label :content, "コメント" %><br />
              <%= f.text_area :content, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
            <li class="comments_list">
              <% @comments.each do |comment| %>
                <p>
                  <b><%= comment.content_title %></b>
                  <%= comment.content %>
                  <%= link_to comment.user.name, user_path(comment.user), class: :comment_user %>
                </p>
              <% end %>
            </li>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>